### ISSUE TITLE
[Question] Is richcontext.graph.RCGraph used once the workflow is finished?

### ISSUE THREAD

**Issue by HaritzPuerto** [Coleridge-Initiative/RCGraph#107]
Hi!
I've seen that RCGraph is used to create the jsonld corpus. For example, it's used in `run_step2.py`

But it seems that it's not used in  [corpus.ipynb](https://github.com/Coleridge-Initiative/RCGraph/blob/master/corpus.ipynb)
So I wonder if RCGraph class can be used to explore the data contained by the KG. On the other hand, in corpus.ipynb a graph object is created to visualize the graph
```
nxg = nx.Graph()
```

Maybe the RCGraph is not designed to store data and that's why corpus.ipynb uses the bare jsonld file?

Thanks @ernestogimeno @JasonZhangzy1757

**Comment by ernestogimeno** [comment]
Hi @HaritzPuerto, 

You are correct. RCGraph is used to create the jsonld corpus. The latest code for visualizing the graph is in RCServer repository, you might want to check that out.
